services:
  - type: web
    name: wraplab
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn wraplab.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
